<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <!-- Package Metadata -->
  <name>agilex_piper_controller</name>
  <version>0.1.0</version>
  <description>Standard library for Agilex Piper robotic arm control</description>
  <maintainer email="baoan.du.xj@renesas.com">Baoan Du</maintainer>
  <license>Apache License 2.0</license>

  <!-- Build Dependencies -->
  <buildtool_depend>ament_cmake</buildtool_depend>

  <!-- Build and Execution Dependencies -->
  <depend>eigen</depend>

  <!-- Test Dependencies -->
  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
